{
    slug: 'work-outfits-that-mean-business',
    title: '10 Work Outfits That Mean Business: Office Style Guide 2026',
    category: 'workwear',
    description: 'From power blazers to smart casual Friday — 10 effortlessly chic work outfits for the modern professional woman.',
    readTime: '14 min',
    date: '2026-02-17',
    tag: 'New',
    emoji: '💼',
    affiliateProducts: [
      { name: 'Oversized Wool Blazer', brand: 'Nordstrom', price: '$149', url: 'https://nordstrom.com', tag: 'Editor Pick' },
      { name: 'High-Waisted Trousers', brand: 'ASOS', price: '$58', url: 'https://asos.com', tag: 'Best Value' },
      { name: 'Silk Button-Down Shirt', brand: 'H&M', price: '$45', url: 'https://hm.com' },
      { name: 'Pointed Toe Pumps', brand: 'Nordstrom', price: '$120', url: 'https://nordstrom.com' },
    ],
  },
  {
    slug: 'what-to-wear-date-night',
    title: 'What to Wear on a Date Night: 7 Stunning Looks for Every Occasion',
    category: 'date-night',
    description: 'From fancy dinner to casual coffee — 7 gorgeous date night outfits that will make you feel confident and beautiful.',
    readTime: '11 min',
    date: '2026-02-17',
    tag: 'Trending',
    emoji: '💕',
    affiliateProducts: [
      { name: 'Satin Midi Dress', brand: 'Nordstrom', price: '$89', url: 'https://nordstrom.com', tag: 'Editor Pick' },
      { name: 'Strappy Heeled Sandals', brand: 'ASOS', price: '$62', url: 'https://asos.com' },
      { name: 'Statement Earrings', brand: 'H&M', price: '$18', url: 'https://hm.com', tag: 'Budget Pick' },
      { name: 'Clutch Bag', brand: 'Nordstrom', price: '$55', url: 'https://nordstrom.com' },
    ],
  },
  {
    slug: 'best-jeans-every-body-type',
    title: 'Best Jeans for Every Body Type 2026: The Ultimate Denim Guide',
    category: 'casual',
    description: 'Find your perfect pair — the best jeans for pear, apple, hourglass, athletic, and petite body types.',
    readTime: '15 min',
    date: '2026-02-17',
    tag: 'Popular',
    emoji: '👖',
    affiliateProducts: [
      { name: 'Levi\'s Ribcage Straight', brand: 'Nordstrom', price: '$98', url: 'https://nordstrom.com', tag: 'Best Overall' },
      { name: 'AGOLDE 90s Pinch Waist', brand: 'ShopBop', price: '$198', url: 'https://shopbop.com', tag: 'Best Premium' },
      { name: 'Abercrombie Curve Love', brand: 'Abercrombie', price: '$90', url: 'https://abercrombie.com', tag: 'Best for Curves' },
      { name: 'Good American Good Legs', brand: 'Nordstrom', price: '$159', url: 'https://nordstrom.com' },
      { name: 'H&M Slim Mom Jeans', brand: 'H&M', price: '$35', url: 'https://hm.com', tag: 'Budget Pick' },
    ],
  },
  {
    slug: 'spring-fashion-trends-2026',
    title: 'Spring Fashion Trends 2026: What to Wear This Season',
    category: 'seasonal',
    description: 'The biggest spring 2026 fashion trends and how to style them — from soft pastels to bold statement pieces.',
    readTime: '13 min',
    date: '2026-02-17',
    tag: 'Hot',
    emoji: '🌸',
    affiliateProducts: [
      { name: 'Linen Blend Blazer', brand: 'H&M', price: '$49', url: 'https://hm.com', tag: 'Trend Pick' },
      { name: 'Pleated Midi Skirt', brand: 'ASOS', price: '$45', url: 'https://asos.com' },
      { name: 'Woven Tote Bag', brand: 'Nordstrom', price: '$78', url: 'https://nordstrom.com', tag: 'Must Have' },
      { name: 'Platform Sandals', brand: 'ASOS', price: '$55', url: 'https://asos.com' },
    ],
  },
